name: build vuepress
on:
  push:
    branches:
      - gh-pages
jobs:
  build-doc:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - name: install pnpm
        run: |
          npm i -g pnpm
      - name: install dependencies
        run: |
          pnpm i --frozen-lockfile
      - name: build
        run: pnpm --filter camaleaohouse build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
